### ISSUE TITLE
laravel/passport v8 support

### ISSUE THREAD

**Issue by narwy** [narwy/laravel-mongodb-passport#2]
Looking into support for v8 laravel/passport 👍

**Comment by narwy** [comment]
Found a few functions that need to be converted over, working on that. dev-master is what I will be working on, feel free to test and report back any issues.

**Comment by jesvinmathew** [comment]
I have the same isue
 narwy/laravel-mongodb-passport 2.0.1 requires laravel/passport ^7.5 -> satisfiable by laravel/passport[v7.5.0, v7.5.1] but these conflict with your requirements or minimum-stability.

**Comment by narwy** [comment]
@jesvinmathew can you share your composer file? Sounds like you've installed v8 outside this package?

**Comment by jesvinmathew** [comment]
Yes
Please check 
https://github.com/jesvinmathew/Laravel-Mongo

**Comment by narwy** [comment]
@jesvinmathew 
Remove `"laravel/passport": "^8.0",` from your composer.
then run `composer require narwy/laravel-mongodb-passport`
